# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tytu\u0142')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('status', models.IntegerField(choices=[(0, 'Niewidoczna'), (1, 'Widoczna - Zablokowane g\u0142osowanie'), (2, 'Widoczna - Odblokowane g\u0142osowanie')], default=0, verbose_name='Status')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Je\u017celi pola b\u0119d\u0105 puste ankieta si\u0119 nie przedawni', null=True, verbose_name='Data rozpocz\u0119cia')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data zako\u0144czenia')),
                ('max_replies', models.IntegerField(blank=True, help_text='Zostaw puste je\u017celi ma by\u0107 nieograniczona', null=True, verbose_name='Maksymalna liczba odpowiedzi')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'verbose_name': 'Ankieta',
                'verbose_name_plural': 'Ankiety',
            },
        ),
    ]
