# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-02 21:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poll.models


class Migration(migrations.Migration):

    replaces = [(b'poll', '0001_initial'), (b'poll', '0002_questiontype'), (b'poll', '0003_question'), (b'poll', '0004_auto_20160716_2257'), (b'poll', '0005_auto_20160717_0054'), (b'poll', '0006_auto_20160717_0058'), (b'poll', '0007_auto_20160717_0101'), (b'poll', '0008_auto_20160717_0105'), (b'poll', '0009_auto_20160717_0119'), (b'poll', '0010_token_voted_at'), (b'poll', '0011_auto_20160717_0129'), (b'poll', '0012_auto_20160717_0130'), (b'poll', '0013_poll_allowed_users'), (b'poll', '0014_auto_20160717_0148'), (b'poll', '0015_auto_20160717_0202'), (b'poll', '0016_auto_20160717_0222'), (b'poll', '0017_poll_allowed_groups'), (b'poll', '0018_auto_20160717_1234'), (b'poll', '0019_auto_20160727_2045'), (b'poll', '0020_auto_20160727_2045'), (b'poll', '0021_vote'), (b'poll', '0022_poll_code'), (b'poll', '0023_auto_20160728_1956'), (b'poll', '0024_auto_20160728_2007'), (b'poll', '0025_auto_20160802_1708'), (b'poll', '0026_auto_20160802_1709'), (b'poll', '0027_poll_list_status'), (b'poll', '0028_poll_auth'), (b'poll', '0029_auto_20160802_1713'), (b'poll', '0030_auto_20160802_1956'), (b'poll', '0031_vote'), (b'poll', '0032_vote_value'), (b'poll', '0033_auto_20160802_2005'), (b'poll', '0034_vote_poll'), (b'poll', '0035_auto_20160802_2332'), (b'poll', '0036_auto_20160803_1654'), (b'poll', '0037_remove_token_voted_at'), (b'poll', '0038_auto_20160803_1808'), (b'poll', '0039_auto_20160803_1809'), (b'poll', '0040_auto_20160806_1516'), (b'poll', '0041_auto_20160806_1600'), (b'poll', '0042_auto_20160806_1624'), (b'poll', '0043_auto_20160808_1917'), (b'poll', '0044_auto_20160808_1922'), (b'poll', '0045_auto_20160823_2059'), (b'poll', '0046_auto_20160824_0809'), (b'poll', '0047_auto_20171202_2246')]

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tytu\u0142')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('status', models.IntegerField(choices=[(0, 'Niewidoczna'), (1, 'Widoczna - Zablokowane g\u0142osowanie'), (2, 'Widoczna - Odblokowane g\u0142osowanie')], default=0, verbose_name='Status')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Je\u017celi pola b\u0119d\u0105 puste ankieta si\u0119 nie przedawni', null=True, verbose_name='Data rozpocz\u0119cia')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data zako\u0144czenia')),
                ('max_replies', models.IntegerField(blank=True, help_text='Zostaw puste je\u017celi ma by\u0107 nieograniczona', null=True, verbose_name='Maksymalna liczba odpowiedzi')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'verbose_name': 'Ankieta',
                'verbose_name_plural': 'Ankiety',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pytanie')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pod tytu\u0142')),
                ('required', models.BooleanField(default=True, verbose_name='Wymagane')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('singlechoice', 'Jednokrotnego wyboru'), ('multichoice', 'Wielokrotnego wyboru'), ('textarea', 'Pole tekstowe'), ('scale', 'skala')], max_length=255, verbose_name='Typ pytania')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_types', to='poll.Poll')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Typ pytania',
                'verbose_name_plural': 'Typy pytan',
            },
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ['order'], 'verbose_name': 'Pytanie', 'verbose_name_plural': 'Pytania'},
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=poll.models.gen_code, max_length=255, unique=True, verbose_name='Kod')),
                ('voted', models.BooleanField(default=False, verbose_name='U\u017cyto?')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='poll.Poll')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
            },
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('singlechoice', 'Jednokrotnego wyboru'), ('multichoice', 'Wielokrotnego wyboru'), ('textarea', 'Pole tekstowe'), ('scale', 'Skala')], max_length=255, verbose_name='Typ pytania'),
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokeny'},
        ),
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Kod'),
        ),
        migrations.AddField(
            model_name='poll',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Osoby kt\xf3re mog\u0105 zobaczy\u0107 i edytowa\u0107 ankiet\u0119'),
        ),
        migrations.AddField(
            model_name='poll',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to=b'auth.Group', verbose_name='Grupy kt\xf3re mog\u0105 zobaczy\u0107 i edytowa\u0107 ankiet\u0119'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('singlechoice', 'Jednokrotnego wyboru'), ('multichoice', 'Wielokrotnego wyboru'), ('textarea', 'Pole tekstowe'), ('scale', 'Skala')], default='singlechoice', max_length=255, verbose_name='Typ pytania'),
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='poll',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255, verbose_name='Wyb\xf3r')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Odpowied\u017ai',
                'verbose_name_plural': 'Odpowied\u017ai',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pytanie')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pod tytu\u0142')),
                ('required', models.BooleanField(default=True, verbose_name='Wymagane')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('SingleChoice', 'Jednokrotnego wyboru'), ('MultiChoice', 'Wielokrotnego wyboru'), ('TextArea', 'Pole tekstowe'), ('Scale', 'Skala'), ('MultiScale', 'Skala wielowierszowa')], default='singlechoice', max_length=255, verbose_name='Typ pytania')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.Poll')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Question'),
        ),
        migrations.AddField(
            model_name='poll',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Klucz'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Niewidoczna'), (1, 'Ukryta')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ukryta'), (1, 'Publikowana')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='poll',
            name='list_status',
            field=models.IntegerField(choices=[(0, 'Ukryta'), (1, 'Publikowana')], default=0, verbose_name='Widoczna na stronie g\u0142\xf3wnej'),
        ),
        migrations.AddField(
            model_name='poll',
            name='auth',
            field=models.IntegerField(choices=[(0, 'Otwarta'), (1, 'Zabezpieczona kluczami (zak\u0142adka tokeny)')], default=0, verbose_name='Typ autoryzacji'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=255, verbose_name='Kod')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.Question')),
                ('value', models.CharField(max_length=255, verbose_name='Warto\u015b\u0107')),
                ('poll', models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.Poll')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 2, 23, 32, 27, 380000))),
            ],
            options={
                'verbose_name': 'Wyb\xf3r',
                'verbose_name_plural': 'Wybory',
            },
        ),
        migrations.RemoveField(
            model_name='poll',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='start_datetime',
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['pk'], 'verbose_name': 'Wyb\xf3r', 'verbose_name_plural': 'Wybory'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Wyb\xf3r', 'verbose_name_plural': 'Wybory'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=poll.models.get_now, editable=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='max_replies',
        ),
        migrations.AlterField(
            model_name='vote',
            name='form_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Kod'),
        ),
    ]
