# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-03 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255, verbose_name='Wybór')),
            ],
            options={
                'verbose_name': 'Odpowiedzi',
                'verbose_name_plural': 'Odpowiedzi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Klucz')),
                ('status', models.IntegerField(choices=[(0, 'Ukryta'), (1, 'Publikowana')], default=0, verbose_name='Status')),
                ('list_status', models.IntegerField(choices=[(0, 'Ukryta'), (1, 'Publikowana')], default=0, verbose_name='Widoczna na stronie głównej')),
                ('auth', models.IntegerField(choices=[(0, 'Otwarta'), (1, 'Zabezpieczona kluczami (zakładka tokeny)')], default=0, verbose_name='Typ autoryzacji')),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupy które mogą zobaczyć i edytować ankietę')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Osoby które mogą zobaczyć i edytować ankietę')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ankieta',
                'verbose_name_plural': 'Ankiety',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pytanie')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pod tytuł')),
                ('required', models.BooleanField(default=True, verbose_name='Wymagane')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('SingleChoice', 'Jednokrotnego wyboru'), ('MultiChoice', 'Wielokrotnego wyboru'), ('TextArea', 'Pole tekstowe'), ('Scale', 'Skala'), ('MultiScale', 'Skala wielowierszowa')], default='singlechoice', max_length=255, verbose_name='Typ pytania')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.Poll')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Kod')),
                ('voted', models.BooleanField(default=False, verbose_name='Użyto?')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='poll.Poll')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokeny',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(db_index=True, max_length=255, verbose_name='Kod')),
                ('value', models.CharField(max_length=255, verbose_name='Wartość')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.Poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.Question')),
            ],
            options={
                'verbose_name': 'Wybór',
                'verbose_name_plural': 'Wybory',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Question'),
        ),
    ]
