# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_squashed_0047_auto_20171202_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.Poll'),
        ),
    ]
