# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-03 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': 'Odpowiedzi', 'verbose_name_plural': 'Odpowiedzi'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='order',
        ),
    ]
