# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ['order'], 'verbose_name': 'Pytanie', 'verbose_name_plural': 'Pytania'},
        ),
    ]
