# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20160716_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=poll.models.gen_code, max_length=255, verbose_name='Kod')),
                ('voted', models.BooleanField(default=False, verbose_name='U\u017cyto?')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='poll.Poll')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('singlechoice', 'Jednokrotnego wyboru'), ('multichoice', 'Wielokrotnego wyboru'), ('textarea', 'Pole tekstowe'), ('scale', 'Skala')], max_length=255, verbose_name='Typ pytania'),
        ),
    ]
