# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20160717_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Kod'),
        ),
    ]
