# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20160717_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(default=poll.models.gen_code, max_length=255, verbose_name='Kod'),
        ),
    ]
