# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20160717_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokeny'},
        ),
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Kod'),
        ),
    ]
