# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20160717_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 17, 1, 28, 35, 278000)),
            preserve_default=False,
        ),
    ]
