# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20160717_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='voted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token u\u017cyto'),
        ),
    ]
