# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0013_poll_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='poll',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_users', to=settings.AUTH_USER_MODEL, verbose_name='Osoby kt\xf3re mog\u0105 zobaczy\u0107 i edytowa\u0107 ankiet\u0119'),
        ),
    ]
