# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 00:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_auto_20160717_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Osoby kt\xf3re mog\u0105 zobaczy\u0107 i edytowa\u0107 ankiet\u0119'),
        ),
    ]
