# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_poll_allowed_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('singlechoice', 'Jednokrotnego wyboru'), ('multichoice', 'Wielokrotnego wyboru'), ('textarea', 'Pole tekstowe'), ('scale', 'Skala')], default='singlechoice', max_length=255, verbose_name='Typ pytania'),
        ),
    ]
