# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='code',
            field=models.CharField(default='AbC', max_length=255, verbose_name='Kod'),
            preserve_default=False,
        ),
    ]
