# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_poll_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Klucz'),
        ),
    ]
