# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0023_auto_20160728_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.Poll'),
        ),
    ]
