# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0024_auto_20160728_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Niewidoczna'), (1, 'Ukryta')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SingleChoice', 'Jednokrotnego wyboru'), ('MultiChoice', 'Wielokrotnego wyboru'), ('TextArea', 'Pole tekstowe'), ('Scale', 'Skala'), ('MultiScale', 'Skala wielowierszowa')], default='singlechoice', max_length=255, verbose_name='Typ pytania'),
        ),
    ]
