# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0025_auto_20160802_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ukryta'), (1, 'Publikowana')], default=0, verbose_name='Status'),
        ),
    ]
