# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0026_auto_20160802_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='list_status',
            field=models.IntegerField(choices=[(0, 'Ukryta'), (1, 'Publikowana')], default=0, verbose_name='Widoczna na stronie g\u0142\xf3wnej'),
        ),
    ]
