# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0028_poll_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='auth',
            field=models.IntegerField(choices=[(0, 'Otwarta'), (1, 'Zabezpieczona kluczami (zak\u0142adka tokeny)')], default=0, verbose_name='Typ autoryzacji'),
        ),
    ]
