# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0029_auto_20160802_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
