# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0030_auto_20160802_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Kod')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.Question')),
            ],
            options={
                'verbose_name': 'Wyb\xf3r',
                'verbose_name_plural': 'Wybory',
            },
        ),
    ]
