# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0032_vote_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='code',
            new_name='form_id',
        ),
    ]
