# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0033_auto_20160802_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.Poll'),
            preserve_default=False,
        ),
    ]
