# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0034_vote_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 2, 23, 32, 27, 380000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Warto\u015b\u0107'),
        ),
    ]
