# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0035_auto_20160802_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='start_datetime',
        ),
    ]
