# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0037_remove_token_voted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['pk'], 'verbose_name': 'Wyb\xf3r', 'verbose_name_plural': 'Wybory'},
        ),
    ]
