# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0038_auto_20160803_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Wyb\xf3r', 'verbose_name_plural': 'Wybory'},
        ),
    ]
