# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0039_auto_20160803_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=poll.models.get_now, editable=False),
        ),
    ]
