# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0040_auto_20160806_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
