# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0043_auto_20160808_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
