# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0044_auto_20160808_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='max_replies',
        ),
        migrations.AlterField(
            model_name='poll',
            name='code',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Klucz'),
        ),
    ]
