# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0045_auto_20160823_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Klucz'),
        ),
    ]
